### ISSUE TITLE
Pytest color is not showing up running as a task

### ISSUE THREAD

**Issue by ashrafuzzaman** [IBM-Cloud/vscode-log-output-colorizer#17]
I created a Test task that runs the `py.test`. [This plugin](https://marketplace.visualstudio.com/items?itemName=sharksym.gen80-colorizer) can show some color but not quit good. But `vscode-log-output-colorizer` do not show color at all.

**Comment by triceam** [comment]
The Python extension is overriding the colorization in the Output panel.  There can only be one active colorizer in the output channel at any time - this is a limitation with VS Code itself.  It's been reported that the Python, Code Runner, and Quokka extensions will cause conflicts.  There are also a few others that I can't remember the names of off hand.  If you want the Output Colorizer to have precedence, then you might have to disable the Python extension (or others).
